name: 💡 Usulan Fitur
description: Sarankan ide atau fitur baru.
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Masalah / kebutuhan
      description: Fitur ini menyelesaikan masalah apa?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solusi yang diusulkan
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatif yang dipertimbangkan
